baseURL = "https://blog.sunmer.top/"
languageCode = "zh-cn"
title = "Xing Fu' Blog"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true

[pagination]
    pagerSize = 6
