baseURL = "https://hhtech.github.io/XingFu-Blog/"
languageCode = "zh-cn"
title = "Xing Fu' Blog"
theme = "hugo-theme-stack"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableRobotsTXT = true
enableGitInfo = true

[pagination]
    pagerSize = 6
