baseURL = "https://hhtech.github.io/XingFu-Blog/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "XingFu Blog"
theme = "beautifulhugo"
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[Params]
  homeTitle = "XingFu Blog"
  subtitle = "使用 Beautiful Hugo 构建，并通过 GitHub Pages 自动发布"
  mainSections = ["post"]
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  selfHosted = true

[Params.author]
  name = "Xing Fu"

[[menu.main]]
  name = "首页"
  url = ""
  weight = 1

[[menu.main]]
  name = "关于"
  url = "page/about/"
  weight = 2

[[menu.main]]
  name = "归档"
  url = "post/"
  weight = 3
