site:
  url: https://hhtech.github.io/XingFu-Blog/
  title: Xing Fu' Blog
  author: Xing Fu' Blog
  description: 记录旧文、随想和新的开始。
  favicon: favicon.png
  pageSize: 6
global:
  avatar: avatar.png
  rss: true
  i18n: false
  search: false
nav:
  - name: 归档
    url: /archives
  - name: 分类
    url: /categories
  - name: 标签
    url: /tags
  - name: 关于
    url: /about
footer:
  copyright:
    owner: Xing Fu' Blog
    time: 2025 - 2026
  beian:
    icp:
      enabled: false
    police:
      enabled: false
index:
  social:
    - name: GitHub
      enabled: true
      url: https://github.com/hhtech
post:
  toc: true
  readingTime: true
  copyright:
    CCLicense:
      BY: true
      NC: true
      SA: true
      ND: false
    url: https://creativecommons.org/licenses/by-nc-sa/4.0
sponsor:
  enabled: false
  alipay:
    enabled: false
  wechat:
    enabled: false
  list: false
comment:
  enabled: false
  artalk:
    enabled: false
tools:
  umami:
    enabled: false
    src: https://cloud.umami.is
    websiteID: ""
